### ISSUE TITLE
Can't find the function "save_dist_stats".

### ISSUE THREAD

**Issue by e175764** [mrc-ide/COVID19_CFR_submission#3]
Hi, I can't find "save_dist_stats" function written in simulate_delays_cfr_tidied.R. 
Is there any package which I need to install ??
Could you please help me ? Thank you.

**Comment by davidmanheim** [comment]
Any update?

**Comment by e175764** [comment]
It worked. Thank you:)

**Comment by Khubayb-afk** [comment]
Hi guys,
How did we fix this?
