### ISSUE TITLE
Instructions for running these algorithms

### ISSUE THREAD

**Issue by mnussbaumer** [mrc-ide/COVID19_CFR_submission#4]
Hi, as someone with no experience in R I would like to know how I can use these scripts to replicate the "Report 12" findings. Thanks

**Comment by bobverity** [comment]
Hi. I'm afraid these scripts will not replicate the Report 12 findings, rather they will replicate the analysis in our paper on estimating the severity of COVID19 (https://doi.org/10.1016/S1473-3099(20)30243-7). Hope that is of some use.

**Comment by mnussbaumer** [comment]
Thanks for the quick reply @bobverity although I'm looking for the algorithms for R12 (I can't find them on Imperial College's resources?).
 Is there any guide to setup&execute these ones?

**Comment by bobverity** [comment]
OK, I've updated the README to give some more details on how to run these scripts. I'm afraid I can't help in terms of providing algorithms for other reports, but all methods and data should be detailed in the report itself. For code availability you'll have to contact the corresponding authors directly.

**Comment by mnussbaumer** [comment]
Hi @bobverity, thank you for the follow up and additions to the readme, even though I haven't yet tried it, it does seem like it has everything needed to get up and running by someone not used to R. I'm closing this :thumbsup:
