### ISSUE TITLE
save_dist_stats

### ISSUE THREAD

**Issue by Khubayb-afk** [mrc-ide/COVID19_CFR_submission#5]
I am running the programme simulate_delays_cfr_tidied.R and the following 'save_dist_stats' is not found.

**Comment by bobverity** [comment]
Thanks, I found the missing file containing the 'save_dist_stats()' function and added it to the repo. Sorry for the inconvenience.

**Comment by Khubayb-afk** [comment]
Thanks mate, will be running it soon so will let you know if i encounter
any issues.

Many thanks,
Khubayb
